services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rozaniec\RozaniecBundle\:
        resource: '../src/'
        exclude: '../src/{Entity,Model,Notification}'

    Rozaniec\RozaniecBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Rozaniec\RozaniecBundle\Twig\RozaniecExtension:
        arguments:
            $baseTemplate: '%rozaniec.base_template%'
            $resolver: '@Rozaniec\RozaniecBundle\Service\RozaniecUserResolver'
        tags: ['twig.extension']

    Rozaniec\RozaniecBundle\Service\RozaniecNotifier:
        arguments:
            $emailFrom: '%rozaniec.email_from%'

    Rozaniec\RozaniecBundle\Service\RozaniecUserResolver:
        arguments:
            $fullNameFields: '%rozaniec.user_full_name_fields%'

    Rozaniec\RozaniecBundle\Command\RozaniecMigrateCommand:
        arguments:
            $userClass: '%rozaniec.user_class%'

    Rozaniec\RozaniecBundle\Sms\SerwerSmsTransportFactory:
        tags: ['texter.transport_factory']
